### PR TITLE
Dns requests delay fix

### LINKED ISSUE #387: DNS clean up and dns responses are delayed
DNS clean up and dns responses are delayed sometimes. Select-case will process one of the case blocks at a time, and this selection is random. So removing the select case from dns processing

### PR DESCRIPTION
**Pull request by mary-dcouto**
close #387

### CODE REVIEW

File: service/cziti/dns-proxy.go [hunk 1]
```diff
@@ -350,32 +350,36 @@ outer:
...
+			select {
+			case <-ticker.C:
+				// cleanup requests we didn't get answers for
+				now := time.Now()
+				for k, r := range reqs {
+					if now.After(r.exp) {
+						log.Debugf("a DNS request has expired - enable trace logging and reproduce this issue for more information")
+						log.Tracef("expired DNS req: %s %s", dns.Type(r.req.Question[0].Qtype), r.req.Question[0].Name)
+
+						delete(reqs, k)
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:370]: i might be wrong but i am pretty sure using the reqs map will no longer be threadsafe when it's in go routines like this, right?

**Comment by dovholuknf** [comment]
I don't see what this is going to solve or why. the select should be performant enough. are you able to reproduce this bug now locally? if so I'd really like to understand what happens here, I'm not quite seeing it

File: service/cziti/dns-proxy.go (hunk 1 above)
Comment (mary-dcouto) [reply service/cziti/dns-proxy.go:370]: Yes, I missed it. I will add a lock before updating the map.

**Comment by mary-dcouto** [comment]
I added a log after "case <- time.After(time.Minute):" and tested it locally. this was not getting printed every minute. It was getting printed randomly like 1 minute, 3 minutes, 5 minutes, 20 minutes etc, so I found that there is a delay, in the select case statements, when you have data in more than one channels in the case statements

File: service/cziti/dns-proxy.go (hunk 1 above)
Comment (dovholuknf) [reply service/cziti/dns-proxy.go:370]: i think there's another problem cleaning the go-routines on 380 when the panic on new line 418 triggers due to network events. it will continue to run and might cause trouble. If nothing else it'd be in that for loop forever.

**Comment by dovholuknf** [comment]
could you share where you put that log message? if it's random like that i'm thinking you had it inside the for loop and when it didn't fire it was because there were no requests to process?

I think the real issue is that this event should probably fire every second or every five seconds and not every minute. if it fires every minute a request that comes in "one second" after it just fired would sit there for 59 seconds - be valid and then only be reclaimed after another minute (1m 59s)

what happens if you put that log outside the loop and set this timer to 1 second or 5 seconds without the goroutine cleanups?

**Comment by mary-dcouto** [comment]
I added the log statement before for loop in the case statement for timeout and it is not consistently displayed every minute.

File: service/cziti/dns-proxy.go [hunk 2]
```diff
@@ -320,7 +317,12 @@ outer:
 		if dnsRetryInterval >= 10000 {
 			dnsRetryInterval = 10000
 		}
-		goto outer
+		goto GetUpstream
+	} else {
+		log.Debugf("Upstream DNS dials succeeded.")
+	}
+	if len(upstreamDnsServers) > 0 && len(dnsUpstreams) != 0 && dnsRetryInterval>500 {
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:324]: this whole if can be removed, can't it? also the function called at 325 would have already been called - so this whole block should be removed?

File: service/cziti/dns-proxy.go [hunk 3]
```diff
@@ -320,7 +317,12 @@ outer:
 		if dnsRetryInterval >= 10000 {
 			dnsRetryInterval = 10000
 		}
-		goto outer
+		goto GetUpstream
+	} else {
+		log.Debugf("Upstream DNS dials succeeded.")
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:322]: this log is effectively the same as the one on line 328 and thus, i think this can be removed

File: service/cziti/dns-proxy.go [hunk 4]
```diff
@@ -260,24 +260,21 @@ func cleanDomainsForNrpt() map[string]bool {
...
-	windns.AddNrptRules(domainMap, dnsip.String())
-	log.Infof("Added connection specific domains to NRPT: %v", domainMap)
-
+	windns.FlushDNS() //do this in case the services come back in different order and the ip returned is no longer the same
 	dnsRetryInterval := 500
 
+GetUpstream:
+	upstreamDnsServers := windns.GetUpstreamDNS()
+	log.Infof("starting DNS proxy upstream: %v, local: %v", upstreamDnsServers, localDnsServers)
+	AddDomainSpecificNrpt()
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:276]: assuming the block at line 324 can be removed, i'd argue to just put this function call back to being inline code. it's easier to read inline. if not - this should be renamed to AddConnectionSpecificDomainsToNrpt but I think just keeping the code inline is cleaner?

File: service/cziti/dns-proxy.go [hunk 5]
```diff
@@ -341,69 +344,117 @@ outer:
...
+					err)
+			} else {
+				log.Tracef("Proxied request sent to %v from ipv%d listener", proxy.RemoteAddr(), pr.ipVer)
 			}
 		}
+
 	}
 }
+
+func AddDomainSpecificNrpt() {
```
[the remark this answers is not in the document]
Comment (mary-dcouto) [reply service/cziti/dns-proxy.go]: Removed

File: service/cziti/dns-proxy.go [hunk 6]
```diff
@@ -341,69 +344,117 @@ outer:
...
+	dnsReqChannel := make(chan struct{})
+	ticker := time.NewTicker(5 * time.Second)
+	defer func() {
+		close(dnsReqChannel)
+		log.Tracef("Exiting dns request handling routines.")
+	}()
+	go func() {
+	CleanUpIteration:
+		for {
+			select {
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:369]: i don't think you need this select/case here, can you can just stop the ticker in the defer and thus can just range over the ticker, right?

File: service/cziti/dns-proxy.go [hunk 7]
```diff
@@ -341,69 +344,117 @@ outer:
...
+			case <-ticker.C:
+				if len(reqs) == 0 {
+					continue CleanUpIteration
+				}
+				// cleanup requests we didn't get answers for
+				now := time.Now()
+				dnsReqMutex.Lock()
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:376]: do you think it'd be useful to add a log statement just before and after this lock so we can see how long this took?

File: service/cziti/dns-proxy.go [hunk 8]
```diff
@@ -341,69 +344,117 @@ outer:
...
+						// just mean some other request was processed successfully and removed the entry from the map
+						// log.Tracef("matching request was not found for id:%d. %s %s", reply.Id, dns.Type(reply.Question[0].Qtype), reply.Question[0].Name)
 					}
-				} else {
-					// keep this log but leave commented out. When two listeners are enabled (ipv4/v6) this msg will
-					// just mean some other request was processed successfully and removed the entry from the map
-					// log.Tracef("matching request was not found for id:%d. %s %s", reply.Id, dns.Type(reply.Question[0].Qtype), reply.Question[0].Name)
 				}
+			case <-dnsReqChannel:
+				return
```
Comment (dovholuknf) [inline service/cziti/dns-proxy.go:418]: it'd be good to have a log here to make sure we know when this goroutine exits

File: service/cziti/dns-proxy.go (hunk 6 above)
Comment (mary-dcouto) [reply service/cziti/dns-proxy.go:369]: I tested it that way. When I remove this select/case, ticket will stop ticking, but the go routine is not exiting.

File: service/cziti/dns-proxy.go (hunk 7 above)
Comment (mary-dcouto) [reply service/cziti/dns-proxy.go:377]: Added the trace logs

File: service/cziti/dns-proxy.go (hunk 8 above)
Comment (mary-dcouto) [reply service/cziti/dns-proxy.go:422]: Added trace logs

File: service/cziti/dns-proxy.go (hunk 6 above)
Comment (dovholuknf) [reply service/cziti/dns-proxy.go:369]: how'd you code it up? did you 'range' over the ticker.C ?  this worked for me:  https://play.golang.org/p/MO3ndiv5qR

```
    ticker := time.NewTicker(time.Millisecond * 500)
    go func() {
        for t := range ticker.C {
            fmt.Println("Tick at", t)
        }
    }()

    // Tickers can be stopped like timers. Once a ticker
    // is stopped it won't receive any more values on its
    // channel. We'll stop ours after 1600ms.
    time.Sleep(time.Millisecond * 1600)
    ticker.Stop()
    fmt.Println("Ticker stopped")
```

Comment (mary-dcouto) [reply service/cziti/dns-proxy.go:369]: I added a print statement after the for loop in this example and added a sleep for 5 seconds after the ticker.Stop() function. The print statement after the for loop never got executed. So the go routine is not exiting until the main program exits.

Comment (dovholuknf) [reply service/cziti/dns-proxy.go:369]: Gotcha. That's a bummer, but good to know.

**Review by dovholuknf — APPROVED** [review]
